[#WEB-282]  Add io web section
pagopa/io.italia.it pull request #488
Opened 2023-09-11 12:28 UTC by lordkada

#### List of Changes
Added information related to the new io-web portal and its features

#### Motivation and Context
Provide citizens with more information on how to protect their digital identity with the IO app

#### How Has This Been Tested?
n.p.

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-12-11 09:24 UTC, thisisjp commented on _data/faq.yml
> +    body: Si, puoi farlo [accedendo a questa pagina](https://ioapp.it/it/esci/). Autenticati con SPID o CIE e segui le indicazioni.
```suggestion
    body: Sì, puoi farlo [accedendo a questa pagina](https://ioapp.it/it/esci/). Autenticati con SPID o CIE e segui le indicazioni.
```

2023-12-12 09:01 UTC, vito80ba approved these changes

2023-12-12 09:09 UTC, vito80ba requested changes
Drop console.log please

2023-12-12 11:03 UTC, vito80ba approved these changes

2024-01-26 14:14 UTC, vito80ba approved these changes

2024-01-29 08:50 UTC, merged